SELECT PRO.PRODUCT_CODE, SUM(PRO.PRICE * OFF.SALES_AMOUNT) AS SALES
FROM PRODUCT PRO, OFFLINE_SALE OFF
WHERE PRO.PRODUCT_ID = OFF.PRODUCT_ID
GROUP BY PRO.PRODUCT_CODE
ORDER BY SALES DESC, PRODUCT_CODE ASC;