SELECT RI.REST_ID, RI.REST_NAME, RI.FOOD_TYPE, 
    RI.FAVORITES, RI.ADDRESS, ROUND(AVG(RE.REVIEW_SCORE), 2) AS REVIEW_SCORE
FROM REST_INFO RI, REST_REVIEW RE
WHERE RI.REST_ID = RE.REST_ID AND RI.ADDRESS LIKE '서울%'
GROUP BY RI.REST_ID
ORDER BY REVIEW_SCORE DESC, FAVORITES DESC